/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useFrame, useRef } from "react";

export default function Mazda({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "assets/models/mazda/mazda.gltf"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, 0, 0]}
      scale={1.2}
    >
      <group name="Scene" onClick={() => actions.Action.play()}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="body_7">
                <mesh
                  name="Object_27"
                  geometry={nodes.Object_27.geometry}
                  material={materials.body}
                />
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials.focus}
                />
                <mesh
                  name="Object_29"
                  geometry={nodes.Object_29.geometry}
                  material={materials.body_glass}
                />
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials.body_plastic}
                />
                <mesh
                  name="Object_31"
                  geometry={nodes.Object_31.geometry}
                  material={materials.bumper_light}
                />
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials.chrome}
                />
                <mesh
                  name="Object_33"
                  geometry={nodes.Object_33.geometry}
                  material={materials.signal_light}
                />
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials.body_farme_glass}
                />
              </group>
              <group name="brakediskback_18">
                <mesh
                  name="Object_76"
                  geometry={nodes.Object_76.geometry}
                  material={materials["Material.002"]}
                />
                <mesh
                  name="Object_77"
                  geometry={nodes.Object_77.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="brakediskFL_15"
                position={[0.76, 0.31, 1.21]}
                rotation={[2.36, 0, Math.PI]}
                scale={-1.8}
              >
                <mesh
                  name="Object_65"
                  geometry={nodes.Object_65.geometry}
                  material={materials["Material.004"]}
                />
                <mesh
                  name="Object_66"
                  geometry={nodes.Object_66.geometry}
                  material={materials["Material.003"]}
                />
              </group>
              <group
                name="brakediskFR_13"
                position={[-0.76, 0.31, 1.21]}
                rotation={[-0.78, 0, Math.PI]}
                scale={1.8}
              >
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials["Material.042"]}
                />
                <mesh
                  name="Object_59"
                  geometry={nodes.Object_59.geometry}
                  material={materials["Material.043"]}
                />
              </group>
              <group name="exhaust_5">
                <mesh
                  name="Object_21"
                  geometry={nodes.Object_21.geometry}
                  material={materials.exhaust_focus}
                />
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials.exhaust_chrome}
                />
              </group>
              <group name="kit_2">
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials.kit_paint}
                />
              </group>
              <group
                name="light_1"
                position={[0, 0.67, 1.84]}
                scale={[0.89, 0.78, 2.16]}
              >
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.light_chrome}
                />
                <mesh
                  name="Object_11"
                  geometry={nodes.Object_11.geometry}
                  material={materials.light}
                />
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.body}
                />
                <mesh
                  name="Object_7"
                  geometry={nodes.Object_7.geometry}
                  material={materials.body_glass}
                />
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.body_plastic}
                />
                <mesh
                  name="Object_9"
                  geometry={nodes.Object_9.geometry}
                  material={materials.light_glass}
                />
              </group>
              <group name="list_10">
                <mesh
                  name="Object_49"
                  geometry={nodes.Object_49.geometry}
                  material={materials.texture}
                />
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials.list}
                />
              </group>
              <group name="mirror_3">
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials.mirror_paint}
                />
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials.mirror}
                />
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials.mirror_plastic}
                />
              </group>
              <group name="number_plate_6" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials.numberplate}
                />
                <mesh
                  name="Object_25"
                  geometry={nodes.Object_25.geometry}
                  material={materials.plastic}
                />
              </group>
              <group name="panel_back_light_8">
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials.back_light_plastic}
                />
                <mesh
                  name="Object_37"
                  geometry={nodes.Object_37.geometry}
                  material={materials.back_light_signal_glass}
                />
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials.back_light_glass}
                />
                <mesh
                  name="Object_39"
                  geometry={nodes.Object_39.geometry}
                  material={materials.back_light_glass_goback}
                />
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials.back_light_chrome}
                />
                <mesh
                  name="Object_41"
                  geometry={nodes.Object_41.geometry}
                  material={materials.back_light}
                />
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials.back_light_signal}
                />
                <mesh
                  name="Object_43"
                  geometry={nodes.Object_43.geometry}
                  material={materials.back_light_goback}
                />
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials.material}
                />
              </group>
              <group name="spoiler_4">
                <mesh
                  name="Object_19"
                  geometry={nodes.Object_19.geometry}
                  material={materials.spoiler_paint}
                />
              </group>
              <group name="text_Lexyc16_and_Veisun_0">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.text_L_and_V}
                />
              </group>
              <group name="text_RedSuns_11">
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials.text_color}
                />
              </group>
              <group
                name="wheelFL_14"
                position={[0.76, 0.31, 1.21]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={-1.57}
              >
                <mesh
                  name="Object_61"
                  geometry={nodes.Object_61.geometry}
                  material={materials["tire.002"]}
                />
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials["bl.002"]}
                />
                <mesh
                  name="Object_63"
                  geometry={nodes.Object_63.geometry}
                  material={materials["chrome.002"]}
                />
              </group>
              <group
                name="wheelFR_12"
                position={[-0.76, 0.31, 1.21]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.57}
              >
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials.tire}
                />
                <mesh
                  name="Object_55"
                  geometry={nodes.Object_55.geometry}
                  material={materials.material_36}
                />
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials["chrome.004"]}
                />
              </group>
              <group
                name="wheelRL_17"
                position={[0.76, 0.31, -1.24]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={-1.57}
              >
                <mesh
                  name="Object_72"
                  geometry={nodes.Object_72.geometry}
                  material={materials["tire.003"]}
                />
                <mesh
                  name="Object_73"
                  geometry={nodes.Object_73.geometry}
                  material={materials["bl.003"]}
                />
                <mesh
                  name="Object_74"
                  geometry={nodes.Object_74.geometry}
                  material={materials["chrome.003"]}
                />
              </group>
              <group
                name="wheelRR_16"
                position={[-0.76, 0.31, -1.24]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.57}
              >
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["tire.001"]}
                />
                <mesh
                  name="Object_69"
                  geometry={nodes.Object_69.geometry}
                  material={materials["bl.001"]}
                />
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials["chrome.001"]}
                />
              </group>
              <group name="wiper's_9" rotation={[0, 0, -Math.PI]} scale={-1}>
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["wiper.plastic"]}
                />
                <mesh
                  name="Object_47"
                  geometry={nodes.Object_47.geometry}
                  material={materials["wiper.rubber"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/mazda/mazda.gltf");
