/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lexyc16 (https://sketchfab.com/Lexyc16)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/honda-nsx-1990-1cc15628a00a4739a6b6c01128927c8d
title: Honda NSX 1990
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Honda() {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "assets/models/honda/honda.glb"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group
      ref={group}
      rotation={[0, -Math.PI / 3, 0]}
      dispose={null}
      position={[1, -1, 0]}
      onPointerEnter={() => Object.entries(actions)[30][1].play()}
      onPointerLeave={() => Object.entries(actions)[30][1].stop()}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube002_7" position={[0, 0.96, 2.04]}>
                <mesh
                  name="Object_11"
                  geometry={nodes.Object_11.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.007"]}
                />
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials["Material.002"]}
                />
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.008"]}
                />
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group name="Cube001_6" position={[0, 0.96, 2.04]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  name="Object_5"
                  geometry={nodes.Object_5.geometry}
                  material={materials["Material.004"]}
                />
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_7"
                  geometry={nodes.Object_7.geometry}
                  material={materials["Material.006"]}
                />
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.009"]}
                />
                <mesh
                  name="Object_9"
                  geometry={nodes.Object_9.geometry}
                  material={materials["Material.010"]}
                />
              </group>
              <group
                name="Circle001_9"
                position={[0.69, 0.72, 1.75]}
                rotation={[-0.63, 0, Math.PI / 2]}
                scale={0.16}
              >
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials["Material.011"]}
                />
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.018"]}
                />
                <mesh
                  name="Object_19"
                  geometry={nodes.Object_19.geometry}
                  material={materials["Material.021"]}
                />
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.023"]}
                />
              </group>
              <group name="Cube005_10" position={[0, 0.96, 2.04]}>
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  name="Object_23"
                  geometry={nodes.Object_23.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane_11"
                position={[0, 0.69, 2.18]}
                scale={[0.48, 0.12, 0.12]}
              >
                <mesh
                  name="Object_25"
                  geometry={nodes.Object_25.geometry}
                  material={materials["Material.010"]}
                />
              </group>
              <group
                name="Plane001_13"
                position={[0, 0.7, 2.19]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[-0.24, 0.09, 0.09]}
              >
                <mesh
                  name="Object_27"
                  geometry={nodes.Object_27.geometry}
                  material={materials["Material.010"]}
                />
              </group>
              <group
                name="Cube006_14"
                position={[0, 0.02, 0]}
                scale={[1.05, 1, 1]}
              >
                <mesh
                  name="Object_29"
                  geometry={nodes.Object_29.geometry}
                  material={materials["Material.017"]}
                />
              </group>
              <group
                name="Cube007_15"
                position={[0, 0.76, -0.43]}
                rotation={[0.11, 0, Math.PI]}
                scale={[-0.06, 0.05, 0.06]}
              >
                <mesh
                  name="Object_31"
                  geometry={nodes.Object_31.geometry}
                  material={materials["Material.016"]}
                />
              </group>
              <group name="Cube009_16">
                <mesh
                  name="Object_33"
                  geometry={nodes.Object_33.geometry}
                  material={materials["Material.010"]}
                />
              </group>
              <group name="Cube008_17" position={[0, 0.96, 2.04]}>
                <mesh
                  name="Object_35"
                  geometry={nodes.Object_35.geometry}
                  material={materials["Material.012"]}
                />
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials["Material.014"]}
                />
                <mesh
                  name="Object_37"
                  geometry={nodes.Object_37.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube010_18"
                position={[0, 0.74, 2.19]}
                rotation={[3.14, 0, 0]}
                scale={[-0.06, 0.05, 0.06]}
              >
                <mesh
                  name="Object_39"
                  geometry={nodes.Object_39.geometry}
                  material={materials["Material.016"]}
                />
              </group>
              <group
                name="Circle002_19"
                position={[0.69, 0.72, 0.03]}
                rotation={[-0.63, 0, Math.PI / 2]}
                scale={0.16}
              >
                <mesh
                  name="Object_41"
                  geometry={nodes.Object_41.geometry}
                  material={materials["Material.011"]}
                />
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.018"]}
                />
                <mesh
                  name="Object_43"
                  geometry={nodes.Object_43.geometry}
                  material={materials["Material.021"]}
                />
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.023"]}
                />
              </group>
              <group
                name="Circle003_20"
                position={[-0.69, 0.72, 0.03]}
                rotation={[-2.51, 0, -Math.PI / 2]}
                scale={0.16}
              >
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.011"]}
                />
                <mesh
                  name="Object_47"
                  geometry={nodes.Object_47.geometry}
                  material={materials["Material.018"]}
                />
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials["Material.021"]}
                />
                <mesh
                  name="Object_49"
                  geometry={nodes.Object_49.geometry}
                  material={materials["Material.023"]}
                />
              </group>
              <group
                name="Circle004_21"
                position={[-0.69, 0.72, 1.75]}
                rotation={[-2.51, 0, -Math.PI / 2]}
                scale={0.16}
              >
                <mesh
                  name="Object_51"
                  geometry={nodes.Object_51.geometry}
                  material={materials["Material.011"]}
                />
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials["Material.018"]}
                />
                <mesh
                  name="Object_53"
                  geometry={nodes.Object_53.geometry}
                  material={materials["Material.021"]}
                />
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials["Material.023"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/honda/honda.glb");
