/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Floppy (https://sketchfab.com/fastolfe)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/lancia-fulvia-rallye-5f02ef9e0daf481aba8c8b51216c0a6b
title: Lancia Fulvia rallye
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lancia(props) {
  const { nodes, materials } = useGLTF("assets/models/lancia/lancia.glb");
  return (
    <group
      scale={0.85}
      dispose={null}
      position={[0, -0.5, 0]}
      rotation={[0, 0.5, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[193.71, 68.68, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_INT004_00_feux_int_0.geometry}
              material={materials["00_feux_int"]}
            />
          </group>
          <group
            position={[-143.89, -1.68, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_INT001_00_feux_int_0.geometry}
              material={materials["00_feux_int"]}
            />
          </group>
          <group
            position={[-124.27, -0.87, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_INT002_00_feux_int_0.geometry}
              material={materials["00_feux_int"]}
            />
          </group>
          <group rotation={[0, Math.PI / 2, 0]} scale={100}>
            <mesh
              geometry={nodes.lights_INT003_00_feux_int_0.geometry}
              material={materials["00_feux_int"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_INT_00_feux_int_0.geometry}
              material={materials["00_feux_int"]}
            />
          </group>
          <group rotation={[0, Math.PI / 2, 0]} scale={100}>
            <mesh
              geometry={nodes.lights_EXT003_00_feux_ext_0.geometry}
              material={materials["00_feux_ext"]}
            />
          </group>
          <group
            position={[-124.27, -0.87, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_EXT001_00_feux_ext_0.geometry}
              material={materials["00_feux_ext"]}
            />
          </group>
          <group
            position={[-143.89, -1.68, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_EXT002_00_feux_ext_0.geometry}
              material={materials["00_feux_ext"]}
            />
          </group>
          <group
            position={[193.71, 68.68, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.lights_EXT_00_feux_ext_0.geometry}
              material={materials["00_feux_ext"]}
            />
          </group>
          <group
            position={[-127.16, -0.99, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome001_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[-101.49, 83.21, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome002_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome003_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[-145.42, -1.74, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome008_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome004_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome005_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[193.71, 68.68, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome006_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[192.76, 75.82, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome007_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[-145.42, -1.74, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome024_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome009_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[4.71, 4.46, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome010_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome011_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome012_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome013_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[93.09, 105.16, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome014_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome015_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 3.66, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome016_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome017_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome018_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.15, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome019_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome020_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome021_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[0.74, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome022_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[34.15, 63.79, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome023_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[168.48, 11.1, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome030_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[175.43, 61.64, -71.35]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome025_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[-145.42, -1.74, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome026_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.chrome027_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[191.97, 56.2, -18.79]}
            rotation={[1.07, 1.5, -1.07]}
            scale={282.04}
          >
            <mesh
              geometry={nodes.chrome028_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[191.97, 56.2, -18.79]}
            rotation={[1.07, 1.5, -1.07]}
            scale={282.04}
          >
            <mesh
              geometry={nodes.chrome029_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[193.78, 68.68, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.chrome_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group rotation={[0, Math.PI / 2, 0]} scale={100}>
            <mesh
              geometry={nodes.chrome031_00_chrome_0.geometry}
              material={materials["00_chrome"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.EXTER_00_exter_0.geometry}
              material={materials["00_exter"]}
            />
            <mesh
              geometry={nodes.EXTER_00_exter_0_1.geometry}
              material={materials["00_exter"]}
            />
          </group>
          <group
            position={[4.71, 4.46, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.EXTER001_00_exter_0.geometry}
              material={materials["00_exter"]}
            />
          </group>
          <group
            position={[-0.63, 4.31, -0.02]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.EXTER002_00_exter_0.geometry}
              material={materials["00_exter"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.EXTER003_00_exter_0.geometry}
              material={materials["00_exter"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.glass_00_vitres_0.geometry}
              material={materials["00_vitres"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.glass001_00_vitres_0.geometry}
              material={materials["00_vitres"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.glass002_00_vitres_0.geometry}
              material={materials["00_vitres"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.glass003_00_vitres_0.geometry}
              material={materials["00_vitres"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-105.51, 19.17, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic001_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[158.63, 26.8, 38.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic002_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[112.24, 36.84, -1.63]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic003_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[6.36, 2.97, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic004_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.technic005_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.technic006_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic007_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic008_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.26, 4.03, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic009_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic010_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[0.74, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic011_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic012_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[193.71, 68.68, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic013_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[131.45, 9.7, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic014_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic015_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-145.42, -1.74, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic016_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-274.85, -7.09, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic017_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-274.85, -7.09, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic018_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic019_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[4.71, 4.46, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic020_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-178.55, 57.68, -0.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic021_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-173.04, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic022_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-74.8, 86.6, 37.8]}
            rotation={[-1.55, 0, -0.02]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic023_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-79.5, 85.29, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic024_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.technic025_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-79.44, 88.16, -6.84]}
            rotation={[-1.62, 0.01, -0.31]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic026_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[16.26, 0, 44.12]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic027_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-29.82, 0, 35.98]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.technic028_00_tech_0.geometry}
              material={materials["00_tech"]}
            />
          </group>
          <group
            position={[-75.14, 87.76, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER001_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[10.86, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER002_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[66.12, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 94.4, 100]}
          >
            <mesh
              geometry={nodes.INTER006_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[-26.63, 80.54, 34.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={104.29}
          >
            <mesh
              geometry={nodes.INTER003_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[-8.6, 30.05, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER004_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[-34.28, 77.99, 34.03]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER005_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[3.74, 87.51, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER007_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[0.15, 20.31, 0.07]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[16.21, 122.64, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER008_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[104.8, 87.77, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[9.81, 57.53, 42.47]}
          >
            <mesh
              geometry={nodes.INTER009_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[-18.92, 115.64, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[51.42, 51.42, 20.76]}
          >
            <mesh
              geometry={nodes.INTER010_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[3.74, 87.49, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER011_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[41.06, 93.73, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER012_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group
            position={[3.74, 82.54, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.INTER013_00_inter_0.geometry}
              material={materials["00_inter"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.wheels_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
            <mesh
              geometry={nodes.wheels_00_roues_0_1.geometry}
              material={materials["00_roues"]}
            />
            <mesh
              geometry={nodes.wheels_00_roues_0_2.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group
            position={[16.26, 0, 44.12]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.wheels001_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
            <mesh
              geometry={nodes.wheels001_00_roues_0_1.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group
            position={[-29.82, 0, 35.98]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.wheels002_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
            <mesh
              geometry={nodes.wheels002_00_roues_0_1.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group
            position={[16.26, 0, 44.12]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.wheels003_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group
            position={[-29.82, 0, 35.98]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={100}
          >
            <mesh
              geometry={nodes.wheels004_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.wheels005_00_roues_0.geometry}
              material={materials["00_roues"]}
            />
          </group>
          <group
            position={[-187.61, 47.2, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other001_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[-187.1, 47.28, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other002_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[192.1, 55.54, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other004_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[-188.29, 46.49, -2.38]}
            rotation={[Math.PI / 2, -1.42, Math.PI / 2]}
            scale={[9.15, 7.71, 7.71]}
          >
            <mesh
              geometry={nodes.other003_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[-3.47, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other005_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.other_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[187.69, 57.01, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other006_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[187.69, 57.01, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.other007_00_autres_0.geometry}
              material={materials["00_autres"]}
            />
          </group>
          <group
            position={[192.22, 55.54, 0]}
            rotation={[-Math.PI / 2, 0.07, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.decals001_00_decals_0.geometry}
              material={materials["00_decals"]}
            />
          </group>
          <group
            position={[-1.45, 7.58, 0.02]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.decals003_00_decals_0.geometry}
              material={materials["00_decals"]}
            />
          </group>
          <group
            position={[1.06, 4.31, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.decals002_00_decals_0.geometry}
              material={materials["00_decals"]}
            />
          </group>
          <group
            position={[-12.39, 30.05, 0]}
            rotation={[-Math.PI / 2, -0.04, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.decals004_00_decals_0.geometry}
              material={materials["00_decals"]}
            />
          </group>
          <group
            position={[0, -1.93, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={398.83}
          >
            <mesh
              geometry={nodes.ground_SOL_0.geometry}
              material={materials.material}
            />
          </group>

          <group rotation={[0, Math.PI / 2, 0]} scale={100}>
            <mesh
              geometry={nodes.lights_EXT004_glass_flou_0.geometry}
              material={materials.glass_flou}
            />
          </group>
          <group
            position={[0.33, 0.73, -105.06]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={63.14}
          >
            <mesh
              geometry={nodes.Plane_logo_FB_0.geometry}
              material={materials.logo_FB}
            />
          </group>
          <group
            position={[0.33, 0.73, 103.78]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={206.59}
          >
            <mesh
              geometry={nodes.Plane003_logo_lancia_0.geometry}
              material={materials.logo_lancia}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/lancia/lancia.glb");
