/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: soujagah (https://sketchfab.com/soujagah)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nissan-skyline-aeed89c97d8e4c95b115875064aaa1fd
title: Nissan Skyline
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Nissan(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "assets/models/nissan/nissan.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.009}
      rotation={[0.1, -1, 0]}
      position={[0, -0.4, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="4353681aa517477db27104a59ba89bc7fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Door_L"
                  position={[68.52, 37.85, 66.63]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Door_L_Main_0"
                    geometry={nodes.Door_L_Main_0.geometry}
                    material={materials.Main}
                  />
                  <mesh
                    name="Door_L_Tranparent_0"
                    geometry={nodes.Door_L_Tranparent_0.geometry}
                    material={materials.Tranparent}
                  />
                  <mesh
                    name="Door_L_Leather_0"
                    geometry={nodes.Door_L_Leather_0.geometry}
                    material={materials.Leather}
                  />
                  <mesh
                    name="Door_L_Plastic_0"
                    geometry={nodes.Door_L_Plastic_0.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    name="Door_L_Fabric_0"
                    geometry={nodes.Door_L_Fabric_0.geometry}
                    material={materials.Fabric}
                  />
                </group>
                <group
                  name="Door_R"
                  position={[-68.51, 37.69, 66.65]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group name="Object_18" position={[68.51, 67.34, 44.84]}>
                    <mesh
                      name="Door_R_Main_0"
                      geometry={nodes.Door_R_Main_0.geometry}
                      material={materials.Main}
                    />
                    <mesh
                      name="Door_R_Plastic_0"
                      geometry={nodes.Door_R_Plastic_0.geometry}
                      material={materials.Plastic}
                    />
                    <mesh
                      name="Door_R_Fabric_0"
                      geometry={nodes.Door_R_Fabric_0.geometry}
                      material={materials.Fabric}
                    />
                    <mesh
                      name="Door_R_Leather_0"
                      geometry={nodes.Door_R_Leather_0.geometry}
                      material={materials.Leather}
                    />
                    <mesh
                      name="Door_R_Tranparent_0"
                      geometry={nodes.Door_R_Tranparent_0.geometry}
                      material={materials.Tranparent}
                    />
                  </group>
                </group>
                <group
                  name="Main"
                  position={[0, 82.53, -0.68]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Main_Main_0"
                    geometry={nodes.Main_Main_0.geometry}
                    material={materials.Main}
                  />
                  <mesh
                    name="Main_Fabric_0"
                    geometry={nodes.Main_Fabric_0.geometry}
                    material={materials.Fabric}
                  />
                  <mesh
                    name="Main_Leather_0"
                    geometry={nodes.Main_Leather_0.geometry}
                    material={materials.Leather}
                  />
                  <mesh
                    name="Main_Tranparent_0"
                    geometry={nodes.Main_Tranparent_0.geometry}
                    material={materials.Tranparent}
                  />
                  <mesh
                    name="Main_Plastic_0"
                    geometry={nodes.Main_Plastic_0.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    name="Main_Undersides_0"
                    geometry={nodes.Main_Undersides_0.geometry}
                    material={materials.Undersides}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/nissan/nissan.glb");
